-- Migration: Add missing profile columns and database improvements
-- Created: 2025-11-20

-- Add missing columns to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_designer BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS banner_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT false;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_profiles_is_designer ON profiles(is_designer);
CREATE INDEX IF NOT EXISTS idx_profiles_created_at ON profiles(created_at DESC);

-- Add indexes for designs (verify existing ones)
CREATE INDEX IF NOT EXISTS idx_designs_created_at ON designs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_designs_minted_at ON designs(minted_at DESC);

-- Add full-text search support for designs
ALTER TABLE designs ADD COLUMN IF NOT EXISTS search_vector tsvector;

-- Create index for full-text search
CREATE INDEX IF NOT EXISTS designs_search_idx ON designs USING GIN(search_vector);

-- Create function to update search vector
CREATE OR REPLACE FUNCTION designs_search_trigger() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', COALESCE(NEW.name, '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(array_to_string(NEW.tags, ' '), '')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS designs_search_update ON designs;
CREATE TRIGGER designs_search_update
  BEFORE INSERT OR UPDATE ON designs
  FOR EACH ROW EXECUTE FUNCTION designs_search_trigger();

-- Update existing records with search vector
UPDATE designs SET search_vector = 
  setweight(to_tsvector('english', COALESCE(name, '')), 'A') ||
  setweight(to_tsvector('english', COALESCE(description, '')), 'B') ||
  setweight(to_tsvector('english', COALESCE(array_to_string(tags, ' '), '')), 'C')
WHERE search_vector IS NULL;

-- Create analytics tables
CREATE TABLE IF NOT EXISTS design_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  design_id BIGINT REFERENCES designs(id) ON DELETE CASCADE,
  viewer_address TEXT,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_design_views_design_id ON design_views(design_id);
CREATE INDEX IF NOT EXISTS idx_design_views_viewed_at ON design_views(viewed_at DESC);

-- Create designer stats table
CREATE TABLE IF NOT EXISTS designer_stats (
  wallet_address TEXT PRIMARY KEY REFERENCES profiles(wallet_address) ON DELETE CASCADE,
  total_designs INTEGER DEFAULT 0,
  total_mints INTEGER DEFAULT 0,
  total_views INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create function to update designer stats
CREATE OR REPLACE FUNCTION update_designer_stats() RETURNS trigger AS $$
BEGIN
  INSERT INTO designer_stats (wallet_address, total_designs, total_mints)
  VALUES (NEW.owner_address, 1, CASE WHEN NEW.status = 'minted' THEN 1 ELSE 0 END)
  ON CONFLICT (wallet_address) DO UPDATE SET
    total_designs = designer_stats.total_designs + 1,
    total_mints = designer_stats.total_mints + CASE WHEN NEW.status = 'minted' THEN 1 ELSE 0 END,
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for designer stats
DROP TRIGGER IF EXISTS update_stats_on_design_insert ON designs;
CREATE TRIGGER update_stats_on_design_insert
  AFTER INSERT ON designs
  FOR EACH ROW EXECUTE FUNCTION update_designer_stats();

-- Enable RLS on new tables
ALTER TABLE design_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE designer_stats ENABLE ROW LEVEL SECURITY;

-- Create policies for design_views
DROP POLICY IF EXISTS "Anyone can view design views" ON design_views;
CREATE POLICY "Anyone can view design views" ON design_views FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can insert design views" ON design_views;
CREATE POLICY "Anyone can insert design views" ON design_views FOR INSERT WITH CHECK (true);

-- Create policies for designer_stats
DROP POLICY IF EXISTS "Anyone can view designer stats" ON designer_stats;
CREATE POLICY "Anyone can view designer stats" ON designer_stats FOR SELECT USING (true);

-- Add comment for documentation
COMMENT ON TABLE design_views IS 'Tracks views of designs for analytics';
COMMENT ON TABLE designer_stats IS 'Aggregated statistics for designers';
COMMENT ON COLUMN profiles.is_designer IS 'Whether the user is registered as a designer on-chain';
COMMENT ON COLUMN profiles.verified IS 'Whether the profile has been verified by platform admins';
COMMENT ON COLUMN designs.search_vector IS 'Full-text search vector for design name, description, and tags';
